### ISSUE TITLE
"'tuple' object has no attribute 'total'" error when running train.py

### ISSUE THREAD

**Issue by svsambandam** [KeunwooPark/siren-jax#2]
Hi! I am trying to train the siren and ran into this bug:

```
python train.py --file reference.jpg

Traceback (most recent call last):
  File "train.py", line 113, in <module>
    main(args)
  File "train.py", line 62, in main
    model = Model(layers, args.nc, args.omega)
  File "/ubc/cs/research/kmyi/svsamban/research/siren-jax/siren/model.py", line 22, in __init__
    self.net = self.create_network(layers, n_channel, omega)
  File "/ubc/cs/research/kmyi/svsamban/research/siren-jax/siren/model.py", line 51, in create_network
    return Siren(2, layers, n_channel, omega)
  File "/ubc/cs/research/kmyi/svsamban/research/siren-jax/siren/network.py", line 45, in __init__
    net_params, net_apply = create_mlp(input_dim, layers, output_dim, omega)
  File "/ubc/cs/research/kmyi/svsamban/research/siren-jax/siren/network.py", line 30, in create_mlp
    out_shape, net_params = net_init_random(rng, in_shape)
  File "/scratch/soft/anaconda3/envs/nerfies-siren/lib/python3.8/site-packages/jax/experimental/stax.py", line 295, in init_fun
    input_shape, param = init_fun(layer_rng, input_shape)
  File "/ubc/cs/research/kmyi/svsamban/research/siren-jax/siren/layer.py", line 14, in init_fun
    W, b = W_init(k1, (input_shape[-1], out_dim)), b_init(
  File "/ubc/cs/research/kmyi/svsamban/research/siren-jax/siren/initializer.py", line 18, in init
    fan_in, fan_out = _compute_fans(shape, in_axis, out_axis)
  File "/scratch/soft/anaconda3/envs/nerfies-siren/lib/python3.8/site-packages/jax/_src/nn/initializers.py", line 49, in _compute_fans
    receptive_field_size = shape.total / shape[in_axis] / shape[out_axis]
AttributeError: 'tuple' object has no attribute 'total'
(nerfies-siren) svsamban@salty:/ubc/cs/research/kmyi/svsamban/research/siren-jax$ 

```
I am using jax version 0.2.20  and jaxlib version 0.1.69+cuda111 with tensorflow 2.4.0.I have a ubuntu 20.04 system with cuda 11.4. If you have any insight on how to circumvent this error please let me know! 

Thanks!

**Comment by KeunwooPark** [comment]
Hi.

Thanks for letting me know about this issue.
It seems like Jax has been changed from when I initially wrote these codes.

I updated the codes and now you can run the training.
